name = "LocalHilbertBurch"
uuid = "9e134104-6c8f-43ea-a53e-fc3fda40cbb2"
authors = ["Anna-Lena Winz <annalena.winz@googlemail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
