name = "LocalHilbertBurch"
uuid = "9e134104-6c8f-43ea-a53e-fc3fda40cbb2"
authors = ["Anna-Lena Winz <annalena.winz@googlemail.com>", "Roser Homs Pons <rhoms@crm.cat>"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"

[compat]
julia = "1.6"
Oscar = "0.11,0.12"
Documenter = "0.27"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
